mysite/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(), name='login'),
    path('', RedirectView.as_view(url='/polls/', permanent=True)),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import UserDelete

app_name = 'polls'
urlpatterns = [
    path('delete_account/', views.UserDelete.as_view(), name='delete_account'),
    path('update_account/', views.UpdateDate.as_view(), name='update_account'),
    path('personal_account/', views.PersonalAccount.as_view(), name='personal_account'),
    path('', views.IndexView.as_view(), name='home_page'),
    path('/', views.DetailView.as_view(), name='detail'),
    path('results/', views.ResultsView.as_view(), name='results'),
    path('vote/', views.vote, name='vote'),
    path('register', views.RegisterUser.as_view(), name='register'),
]

polls/models.py
import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class User(AbstractUser):
    avatar = models.ImageField(blank=False, upload_to="images/avatar", verbose_name="avatar")


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    content = models.TextField(max_length=5000)
    summary_content = models.TextField(max_length=1000)
    image = models.ImageField(blank=True, upload_to="images/avatar")
    question_votes = models.IntegerField(default=0)

    @property
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

    def procent(self):
        return 100 * self.votes / self.question.question_votes


class Vote(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

polls/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from polls.models import User


class Registration(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'avatar']

polls/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import CreateView

from .forms import Registration
from .models import Question, Choice, Vote, User
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.views import generic


class IndexView(generic.ListView):
    template_name = 'polls/home_page.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'вы не сделали выбор'
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        question.question_votes += 1
        question.question_votes.save()
        user_choice = Vote.objects.create(question=question, user=request.user)
        user_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class RegisterUser(CreateView):
    form_class = Registration
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')
    success_page = 'registration'


class PersonalAccount(generic.ListView):
    model = User
    template_name = 'polls/personal_account.html'


class UpdateDate(LoginRequiredMixin, generic.UpdateView):
    model = User
    template_name = 'polls/update_account.html'
    success_url = '/'
    fields = ('username', 'avatar')

    def get_object(self, queryset=None):
        objs = super(UpdateDate, self).get_object(queryset)
        if objs != self.request.user:
            raise PermissionDenied()
        else:
            return self.request.user


class UserDelete(generic.DetailView):
    model = User
    template_name = 'polls/delete_account.html'
    success_url = reverse_lazy('polls:home_page')

polls/templates/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block sidebar %}
        <nav>
            <a href="{% url 'polls:home_page' %}">Главная</a>
                {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Выйти</a>
                <a href="{% url 'polls:personal_account' %}">Личный кабинет</a>
                {% else %}
                <a href="{% url 'polls:register' %}">Регистрация</a>
                <a href="{% url 'login' %}">Войти</a>
                {%endif%}
        </nav>
    {% endblock %}

    {% block content %}

    {% endblock %}
</body>
</html>

polls/templates/polls/delete_account.html
{% extends 'base_template.html' %}

{% block content %}

<div>
    <h3>Delete user {{ user.username }}</h3>
    <p>Do you really want to delete your account?</p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete!">
    </form>
</div>

{% endblock %}

polls/templates/polls/detail.html
{% extends 'base_template.html' %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>{{question.question_text}}</h1>
        </legend>
        {% if error_message %}<p><strong> {{error_message}}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
        {% endfor %}
    </fieldset>
<input type="submit" value="Vote">
</form>

polls/templates/polls/home_page.html
{% extends 'base_template.html' %}

{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a> </li>
    {% endfor %}
</ul>
    {% else %}
     <p>
         Нет вопросов!
     </p>

{% endif %}

polls/templates/polls/personal_account.html
{% extends 'base_template.html' %}

{% block content %}
  <div>
      <img src="{{ user.avatar.url }}">
      <div>
          <p></p>
          <a href="{% url 'polls:update_account' %}"><button type="submit" >Редактировать данные</button></a>
          <button type="submit">Удалить аккаунт</button>
      </div>
  </div>
{% endblock %}

polls/templates/polls/results.html
{% extends 'base_template.html' %}

<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail'  question.id %}">выбрать еще раз? </a>

polls/templates/polls/update_account.html
{% extends 'base_template' %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить изменения</button>
    </form>
{% endblock %}